name = "websocket"
version = "1.0.0"
target = "erlang"

description = "Websocket client in Gleam based on websocks"
licences = ["Apache-2.0"]
# repository = { type = "github", user = "", repo = "" }
# links = [{ title = "Website", href = "" }]
#
# For a full reference of all the available options, you can have a look at
# https://gleam.run/writing-gleam/gleam-toml/.

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
glisten = ">= 9.0.0 and < 10.0.0"
gleam_http = ">= 4.3.0 and < 5.0.0"
gleam_otp = ">= 1.2.0 and < 2.0.0"
websocks = ">= 2.0.0 and < 3.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
